### ISSUE TITLE
Laravel upgrade to 5.4

### ISSUE THREAD

**Issue by ghost** [lakshmajim/twilio#1]
Can't upgrade Laravel to 5.4
Call to undefined method Illuminate\Foundation\Application::share()
As of laravel 5.4 share has been removed. You will have to use the singleton instead.

**Comment by lakshmaji** [comment]
Hi @trixanapp 

Thank you very much for your support, we will update it to be compatible with Laravel 5.4 with reference to your suggestion #1. If you want to contribute you can create a pull request.

**Comment by ghost** [comment]
possible to do so:
in file TwilioServiceProvider
public function register()
{
	if (method_exists(\Illuminate\Foundation\Application::class, 'singleton')) { // for laravel 5.4
		$this->app->singleton('twilio', function($app) {
			return new Twilio;
		});
	} else { // for laravel <= 5.3
		$this->app['twilio'] = $this->app->share(function($app) {
			return new Twilio;
		});
	}
}

**Comment by lakshmaji** [comment]
Hi @trixanapp

We have resolved the upgrade conflict. Your code helped  me a lot ..
Thank you..........
